### PR TITLE
Use non-fatal input checks for view operator

### LINKED ISSUE #9130: View op asserts should use non-fatal input checks
### 🐛 Describe the bug

The current implementation of the view operator ([et_view.cpp](https://github.com/pytorch/executorch/blob/main/kernels/prim_ops/et_view.cpp#L79)) uses ET_CHECK macros to check input args. This has the effect of unrecoverably crashing the process when input checks fail. We have observed this on an internal app, where a check failure causes a full app crash.

The kernel should use non-fatal ET_KERNEL_CHECK assertions (logging and returning an error code, rather than calling abort), similar to other portable ops. This allows the caller to gracefully handle model execution failures. See https://github.com/pytorch/executorch/pull/2115/files for an example of how other kernels were updated to use ET_KERNEL_CHECK instead of ET_CHECK macros.

### Versions

N/A

cc @larryliu0820 @manuelcandales

### PR DESCRIPTION
**Pull request by zhenyan-zhang-meta**
### Summary
Fixes #9130

Use non-fatal input checks for view operator, just like https://github.com/pytorch/executorch/pull/2115/files, since there are existing cases that an internal app crashed due to a check failure.

Test is updated as well for `RegisterPrimOpsTest`.

### Test plan
Pass updated test:
```
mkdir cmake-out && cd cmake-out && cmake -DEXECUTORCH_BUILD_TESTS=ON .. && cmake --build . --target kernels_prim_ops_test -j9 && ctest -R kernels_prim_ops_test
```

Pass existing CI/CD.

cc @GregoryComer

### CODE REVIEW

File: kernels/prim_ops/et_view.cpp [hunk 1]
```diff
@@ -72,28 +72,38 @@ void et_view(KernelRuntimeContext& context, EValue** stack) {
   auto size = (*stack[1]).toIntList();
   auto out = (*stack[2]).toTensor();
 
-  ET_CHECK(tensors_have_same_dtype(self, out));
+  ET_KERNEL_CHECK(
+      context, tensors_have_same_dtype(self, out), InvalidArgument, );
```
Comment (Gasoonjia) [inline kernels/prim_ops/et_view.cpp:76]: plz remove the extra `,`; same as below

File: kernels/prim_ops/et_view.cpp [hunk 2]
```diff
@@ -72,28 +72,38 @@ void et_view(KernelRuntimeContext& context, EValue** stack) {
...
 
   // Update data ptr
-  ET_CHECK_MSG(
+  ET_KERNEL_CHECK_MSG(
+      context,
       internal::set_tensor_data(
           out,
           /*buffer=*/self.mutable_data_ptr(),
           /*buffer_size=*/out.nbytes()) == Error::Ok,
+      InvalidArgument,
```
Comment (Gasoonjia) [inline kernels/prim_ops/et_view.cpp:105]: @manuelcandales know better, but I'm thinking we should use `Internal` here?

File: kernels/prim_ops/et_view.cpp (hunk 1 above)
Comment (zhenyan-zhang-meta) [reply kernels/prim_ops/et_view.cpp:76]: The commas has to be there since it needs an extra, though empty, param passed in for `retval` (return value).

Similar commas can be seen in main branch: https://github.com/pytorch/executorch/blob/bb3b623fe00c1d962f8012df5097b290fa9a108e/kernels/optimized/cpu/op_add.cpp#L47-L50

Comment (Gasoonjia) [reply kernels/prim_ops/et_view.cpp:76]: oh yeah you're right i forgot that. Thanks for noticing!

File: kernels/prim_ops/et_view.cpp (hunk 2 above)
Comment (zhenyan-zhang-meta) [reply kernels/prim_ops/et_view.cpp]: Updated as suggested.

**Review by swolchok — APPROVED** [review]
shipit (when tests are green)

**Comment by mergennachin** [comment]
Hi, @zhenyan-zhang-meta 
Can you add a corresponding test to exercise the code?

**Comment by zhenyan-zhang-meta** [comment]
> Hi, @zhenyan-zhang-meta Can you add a corresponding test to exercise the code?

Sure, actually I am exploring how to run the relevant tests locally and some of them needs to be updated based on the failed signals.

**Comment by zhenyan-zhang-meta** [comment]
I think the current 3 failing checks left are not relevant to the changes I made.

**Review by GregoryComer — APPROVED** [review]
Looks good to me. Thanks for taking this!
