### PR TITLE
Fix sigmoid operator to support boolean tensor inputs

### LINKED ISSUE #13492: ExecuTorch execution failed for sigmoid.default
### 🐛 Describe the bug

FACTO Generated meta_tuple:
```
['ArgType.Tensor torch.bool (4, 7, 1, 1, 7, 2)']
```

error:
```
[op_sigmoid.cpp:25] Check failed (in.scalar_type() != ScalarType::Bool): 
[method.cpp:1338] KernelCall failed at instruction 0:0 in operator aten::sigmoid.out: 0x12
[method.cpp:1344] arg 0 with type id 1
[method.cpp:1344] arg 1 with type id 1
[method.cpp:1344] arg 2 with type id 1
```

### Versions

nightly

cc @larryliu0820

### PR DESCRIPTION
**Pull request by notkisk**
This PR fixes the issue where boolean tensors were rejected by the `sigmoid` operator in ExecuTorch.
Specifically, it removes the rejection check for boolean tensors in `op_sigmoid.cpp` and adds proper conversion logic:

* `true` → `1.0` → `sigmoid(1.0) ≈ 0.731059`
* `false` → `0.0` → `sigmoid(0.0) = 0.5`

This resolves the failure reported in **#13492**, where a boolean tensor with shape `(4, 7, 1, 1, 7, 2)` could not be processed by `sigmoid.default`.

### Changes

* Removed boolean rejection check in `op_sigmoid.cpp`.
* Added boolean-to-float conversion logic (`true -> 1.0`, `false -> 0.0`) before applying sigmoid.
* Added comprehensive boolean tensor tests in `op_sigmoid_test.cpp`.

### Fixes

Fixes #13492 

### Test Plan

* Added new unit tests in `op_sigmoid_test.cpp` to validate behavior with boolean tensors.
* Verified that boolean tensors now produce correct sigmoid outputs without rejection.

### CODE REVIEW

**Comment by notkisk** [comment]
@manuelcandales @swolchok

**Review by swolchok — CHANGES_REQUESTED** [review]
This PR appears to add trailing whitespace. Can you please fix that so it's easier to see what lines changed?

File: kernels/test/op_sigmoid_test.cpp [hunk 1]
```diff
@@ -50,6 +50,38 @@ class OpSigmoidOutTest : public OperatorTest {
...
+    TensorFactory<OUTPUT_DTYPE> tf_out;
+
+    const std::vector<int32_t> sizes = {2, 2};
+
+    // Destination for the sigmoid operator.
+    Tensor out = tf_out.zeros(sizes);
+
+    // Test with boolean tensor: [True, False, True, False]
+    // True should convert to 1.0 and produce sigmoid(1.0) ≈ 0.731059
+    // False should convert to 0.0 and produce sigmoid(0.0) = 0.5
```
Comment (swolchok) [inline kernels/test/op_sigmoid_test.cpp]: please remove comments like this one that repeat the code

File: kernels/portable/cpu/op_sigmoid.cpp [hunk 2]
```diff
@@ -18,49 +18,74 @@ namespace native {
...
+            const auto input_float = static_cast<CTYPE_COMPUTE>(val_in ? 1.0 : 0.0);  
+            const auto one = static_cast<CTYPE_COMPUTE>(1.0);  
+            auto out_val = one / (one + executorch::math::exp(-input_float));  
+            return out_val;  
+          },  
+          ctx,  
+          in,  
+          utils::SupportedTensorDtypes::BOOL,  
+          out);  
+    } else {
```
Comment (swolchok) [inline kernels/portable/cpu/op_sigmoid.cpp]: I didn't understand why we needed this change, so I checked this PR out locally to get the tests, reverted op_sigmoid.cpp, and just removed lines 24 and 25 where we cause a failure if the input type is bool. This seems to make the tests pass. Why do we need these other changes in op_sigmoid.cpp?

Comment (notkisk) [reply kernels/portable/cpu/op_sigmoid.cpp]: yu're absolutely right! the existing REALHBBF16 support already handles boolean tensors correctly 
 I only needed to remove the rejection check. thanks for catching that

**Review by manuelcandales — APPROVED** [review]

File: kernels/portable/cpu/op_sigmoid.cpp (hunk 2 above)
Comment (notkisk) [reply kernels/portable/cpu/op_sigmoid.cpp]: @swolchok

**Comment by swolchok** [comment]
can you please rebase and run `lintrunner init && lintrunner -a`?

**Comment by notkisk** [comment]
> can you please rebase and run `lintrunner init && lintrunner -a`?

rebased, no lint issues found!

image

**Comment by swolchok** [comment]
hm, I'm not sure why lintrunner is failing. I'll try to repro soon.

**Comment by swolchok** [comment]
the lintrunner message in CI is formatted a bit oddly, but I repro lintrunner not being clean:

```
~/src/executorch> lintrunner
Warning: Could not find a lintrunner config at: '.lintrunner.private.toml'. Continuing without using configuration file.
  FLAKE8 success!
  UFMT success!
  CLANGFORMAT failure
  CMAKEFORMAT success!
  CMAKE success!
  ETCAPITAL success!
  NEWLINE success!
  NOSTDINC success!
  NOTORCHINC success!
  MYPY success!
  LICENSELINT success!
  TORCH_AO_IMPORT success!


>>> Lint for kernels/test/op_sigmoid_test.cpp:

  Warning (CLANGFORMAT) format
    See https://clang.llvm.org/docs/ClangFormat.html.
    Run `lintrunner -a` to apply this patch.

    You can run `lintrunner -a` to apply this patch.

    62  62 |     op_sigmoid_out(tf.make(sizes, /*data=*/{true, false, true, false}), out);
    63  63 |
    64  64 |     EXPECT_TENSOR_CLOSE(
    64     |-        out,
    65     |-        tf_out.make(sizes, /*data=*/{0.731059, 0.5, 0.731059, 0.5}));
        65 |+        out, tf_out.make(sizes, /*data=*/{0.731059, 0.5, 0.731059, 0.5}));
    67  66 |
    68  67 |     out = tf_out.zeros({3});
    69  68 |     op_sigmoid_out(tf.make({3}, /*data=*/{true, true, true}), out);
```

**Comment by notkisk** [comment]
> the lintrunner message in CI is formatted a bit oddly, but I repro lintrunner not being clean:
> 
> ```
> ~/src/executorch> lintrunner
> Warning: Could not find a lintrunner config at: '.lintrunner.private.toml'. Continuing without using configuration file.
>   FLAKE8 success!
>   UFMT success!
>   CLANGFORMAT failure
>   CMAKEFORMAT success!
>   CMAKE success!
>   ETCAPITAL success!
>   NEWLINE success!
>   NOSTDINC success!
>   NOTORCHINC success!
>   MYPY success!
>   LICENSELINT success!
>   TORCH_AO_IMPORT success!
> 
> 
> >>> Lint for kernels/test/op_sigmoid_test.cpp:
> 
>   Warning (CLANGFORMAT) format
>     See https://clang.llvm.org/docs/ClangFormat.html.
>     Run `lintrunner -a` to apply this patch.
> 
>     You can run `lintrunner -a` to apply this patch.
> 
>     62  62 |     op_sigmoid_out(tf.make(sizes, /*data=*/{true, false, true, false}), out);
>     63  63 |
>     64  64 |     EXPECT_TENSOR_CLOSE(
>     64     |-        out,
>     65     |-        tf_out.make(sizes, /*data=*/{0.731059, 0.5, 0.731059, 0.5}));
>         65 |+        out, tf_out.make(sizes, /*data=*/{0.731059, 0.5, 0.731059, 0.5}));
>     67  66 |
>     68  67 |     out = tf_out.zeros({3});
>     69  68 |     op_sigmoid_out(tf.make({3}, /*data=*/{true, true, true}), out);
> ```

done!

**Review by swolchok — APPROVED** [review]
OK, the CI results look sufficient to land. Apparently I need to accept because I previously requested changes, so doing that.
